<a href="https://colab.research.google.com/github/vishurudratrainer/notebooks/blob/main/20june2025jpmc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#HTTP
#FLASK
#Scraping
#Testing
#Multithreading
#Misc

In [ ]:
#requests
#get dat from web
#download data

In [16]:
import requests
response =requests.get("https://jsonplaceholder.typicode.com/todos/")
print(response.ok)
#print(response.text)

True

In [ ]:
response=requests.get('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv')
csvdata=response.text
with open("iris.csv","w") as f:
    f.write(csvdata)

In [ ]:
response=requests.get("https://www.w3schools.com/xml/cd_catalog.xml")
xmldata=response.text
with open("cd_catalog.xml","w") as f:
    f.write(xmldata)

In [ ]:
import pandas as pd

In [ ]:
df1=pd.read_xml("https://www.w3schools.com/xml/cd_catalog.xml")

In [ ]:
#HTTP =---protocol
#Http Request
#Http response
#200,201,304
#404,400,500
#Http method
#GET ---fetching.sensitive
#Post--message body,insert
#PUT updating
#Delete

In [ ]:
jsondata={"title":"Hello","userId":10,"body":"hello"}
response=requests.post('https://jsonplaceholder.typicode.com/posts',json=jsondata,headers={"content-type":"application/json"})
print(response.ok)
print(response.text)

True
{
  "title": "Hello",
  "userId": 10,
  "body": "hello",
  "id": 101
}

In [ ]:
jsondata={"name": "Jonny","job":"MD"}
response=requests.post("https://reqres.in/api/users",json=jsondata,headers={"x-api-key":"reqres-free-v1"})
print(response.ok)
print(response.text)

True
{"name":"Jonny","job":"MD","id":"922","createdAt":"2025-06-20T05:11:52.852Z"}

In [ ]:
jsondata={"email": "eve.holt@reqres.in","password":"cityslicka"}
response=requests.post("https://reqres.in/api/login",json=jsondata,headers={"x-api-key":"reqres-free-v1"})
print(response.ok)
print(response.json()["token"])

True
QpwL5tke4Pnpja7X4

In [ ]:
response=requests.delete("https://reqres.in/api/users/2",headers={"x-api-key":"reqres-free-v1"})
print(response.text)
print(response.ok)

True

In [17]:
import requests
#the website URL
url_link = "https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States"
result = requests.get(url_link).text

In [2]:
from bs4 import BeautifulSoup

In [29]:
url_link="https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States"

result=requests.get(url_link).text

doc=BeautifulSoup(result, "html.parser")

In [30]:
anchorTags =doc.find_all("a")

In [31]:
#for anchor in anchorTags:
 #   print(anchor.text,anchor.attrs['href'])

In [32]:
table1= doc.select("#mw-content-text > div.mw-content-ltr.mw-parser-output > table:nth-child(21) > tbody > tr:nth-child(3) > td:nth-child(3)")

In [33]:
table1

In [34]:
rico=doc.select("#mw-content-text > div.mw-content-ltr.mw-parser-output > table:nth-child(27) > tbody > tr:nth-child(4) > th")

In [35]:
rico

[<th scope="row"><span class="flagicon" style="display:inline-block;width:25px;"><span class="mw-image-border" typeof="mw:File"><span><img alt="" class="mw-file-element" data-file-height="396" data-file-width="738" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/40px-Flag_of_Guam.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/60px-Flag_of_Guam.svg.png 2x" width="23"/></span></span></span> <a href="/wiki/Guam" title="Guam">Guam</a>
 </th>]

In [36]:
import pandas as pd

In [37]:
tableData=pd.read_html(url_link)

In [38]:
len(tableData)

22

In [39]:
tableData[0]

                                                    0
0                 This article is part of a series on
1            Political divisions of the United States
2                                         First level
3   State (Commonwealth) Federal district Territor...
4                                        Second level
5   County / Parish / Borough Unorganized Borough ...
6                                         Third level
7   Township Cities, towns, and villages Cotermino...
8                                        Fourth level
9                                                Ward
10                                        Other areas
11  Protected areas (Conservation district, Nation...
12                               United States portal
13                                                vte

In [40]:
tableData[1]

   Flag, name and postal abbreviation[8]  \
   Flag, name and postal abbreviation[8]
0                                Alabama
1                                 Alaska
2                                Arizona
3                               Arkansas
4                             California
5                               Colorado
6                            Connecticut
7                               Delaware
8                                Florida
9                                Georgia
10                                Hawaii
11                                 Idaho
12                              Illinois
13                               Indiana
14                                  Iowa
15                                Kansas
16                           Kentucky[B]
17                             Louisiana
18                                 Maine
19                              Maryland
20                      Massachusetts[B]
21                              Michigan
22                             Minnesota
23                           Mississippi
24                              Missouri
25                               Montana
26                              Nebraska
27                                Nevada
28                         New Hampshire
29                            New Jersey
30                            New Mexico
31                              New York
32                        North Carolina
33                          North Dakota
34                                  Ohio
35                              Oklahoma
36                                Oregon
37                       Pennsylvania[B]
38                          Rhode Island
39                        South Carolina
40                          South Dakota
41                             Tennessee
42                                 Texas
43                                  Utah
44                               Vermont
45                           Virginia[B]
46                            Washington
47                         West Virginia
48                             Wisconsin
49                               Wyoming

                                                    Cities                  \
   Flag, name and postal abbreviation[8].1         Capital     Largest[12]
0                                       AL      Montgomery      Huntsville
1                                       AK          Juneau       Anchorage
2                                       AZ         Phoenix         Phoenix
3                                       AR     Little Rock     Little Rock
4                                       CA      Sacramento     Los Angeles
5                                       CO          Denver          Denver
6                                       CT        Hartford      Bridgeport
7                                       DE           Dover      Wilmington
8                                       FL     Tallahassee    Jacksonville
9                                       GA         Atlanta         Atlanta
10                                      HI        Honolulu        Honolulu
11                                      ID           Boise           Boise
12                                      IL     Springfield         Chicago
13                                      IN    Indianapolis    Indianapolis
14                                      IA      Des Moines      Des Moines
15                                      KS          Topeka         Wichita
16                                      KY       Frankfort      Louisville
17                                      LA     Baton Rouge     New Orleans
18                                      ME         Augusta        Portland
19                                      MD       Annapolis       Baltimore
20                                      MA          Boston          Boston
21                                      MI         Lansing         Detroit
22                                      MN      Saint Paul     Minneapolis
23                                      MS         Jackson         Jackson
24                                      MO  Jefferson City     Kansas City
25                                      MT          Helena        Billings
26                                      NE         Lincoln           Omaha
27                                      NV     Carson City       Las Vegas
28                                      NH         Concord      Manchester
29                                      NJ         Trenton          Newark
30                                      NM        Santa Fe     Albuquerque
31                                      NY          Albany   New York City
32                                      NC         Raleigh       Charlotte
33                                      ND        Bismarck           Fargo
34                                      OH        Columbus        Columbus
35                                      OK   Oklahoma City   Oklahoma City
36                                      OR           Salem        Portland
37                                      PA      Harrisburg    Philadelphia
38                                      RI      Providence      Providence
39                                      SC        Columbia      Charleston
40                                      SD          Pierre     Sioux Falls
41                                      TN       Nashville       Nashville
42                                      TX          Austin         Houston
43                                      UT  Salt Lake City  Salt Lake City
44                                      VT      Montpelier      Burlington
45                                      VA        Richmond  Virginia Beach
46                                      WA         Olympia         Seattle
47                                      WV      Charleston      Charleston
48                                      WI         Madison       Milwaukee
49                                      WY        Cheyenne        Cheyenne

   Ratification or admission[A] Population (2020)[10] Total area[11]           \
   Ratification or admission[A] Population (2020)[10]            mi2      km2
0                  Dec 14, 1819               5024279          52420   135767
1                   Jan 3, 1959                733391         665384  1723337
2                  Feb 14, 1912               7151502         113990   295234
3                  Jun 15, 1836               3011524          53179   137732
4                   Sep 9, 1850              39538223         163695   423967
5                   Aug 1, 1876               5773714         104094   269601
6                   Jan 9, 1788               3605944           5543    14357
7                   Dec 7, 1787                989948           2489     6446
8                   Mar 3, 1845              21538187          65758   170312
9                   Jan 2, 1788              10711908          59425   153910
10                 Aug 21, 1959               1455271          10932    28313
11                  Jul 3, 1890               1839106          83569   216443
12                  Dec 3, 1818              12812508          57914   149995
13                 Dec 11, 1816               6785528          36420    94326
14                 Dec 28, 1846               3190369          56273   145746
15                 Jan 29, 1861               2937880          82278   213100
16                  Jun 1, 1792               4505836          40408   104656
17                 Apr 30, 1812               4657757          52378   135659
18                 Mar 15, 1820               1362359          35380    91633
19                 Apr 28, 1788               6177224          12406    32131
20                  Feb 6, 1788               7029917          10554    27336
21                 Jan 26, 1837              10077331          96714   250487
22                 May 11, 1858               5706494          86936   225163
23                 Dec 10, 1817               2961279          48432   125438
24                 Aug 10, 1821               6154913          69707   180540
25                  Nov 8, 1889               1084225         147040   380831
26                  Mar 1, 1867               1961504          77348   200330
27                 Oct 31, 1864               3104614         110572   286380
28                 Jun 21, 1788               1377529           9349    24214
29                 Dec 18, 1787               9288994           8723    22591
30                  Jan 6, 1912               2117522         121590   314917
31                 Jul 26, 1788              20201249          54555   141297
32                 Nov 21, 1789              10439388          53819   139391
33                  Nov 2, 1889                779094          70698   183108
34                  Mar 1, 1803              11799448          44826   116098
35                 Nov 16, 1907               3959353          69899   181037
36                 Feb 14, 1859               4237256          98379   254799
37                 Dec 12, 1787              13002700          46054   119280
38                 May 29, 1790               1097379           1545     4001
39                 May 23, 1788               5118425          32020    82933
40                  Nov 2, 1889                886667          77116   199729
41                  Jun 1, 1796               6910840          42144   109153
42                 Dec 29, 1845              29145505         268596   695662
43                  Jan 4, 1896               3271616          84897   219882
44                  Mar 4, 1791                643077           9616    24906
45                 Jun 25, 1788               8631393          42775   110787
46                 Nov 11, 1889               7705281          71298   184661
47                 Jun 20, 1863               1793716          24230    62756
48                 May 29, 1848               5893718          65496   169635
49                 Jul 10, 1890                576851          97813   253335

   Reps.
   Reps.
0      7
1      1
2      9
3      4
4     52
5      8
6      5
7      1
8     28
9     14
10     2
11     2
12    17
13     9
14     4
15     4
16     6
17     6
18     2
19     8
20     9
21    13
22     8
23     4
24     8
25     2
26     3
27     4
28     2
29    12
30     3
31    26
32    14
33     1
34    15
35     5
36     6
37    17
38     2
39     7
40     1
41     9
42    38
43     4
44     1
45    11
46    10
47     2
48     8
49     1

In [41]:
tableData[2]

  Flag, name and postal abbreviation[8]  \
  Flag, name and postal abbreviation[8]
0                  District of Columbia

                                                Established  \
  Flag, name and postal abbreviation[8].1       Established
0                                      DC  Jul 16, 1790[13]

  Population (2020) [10] Total area[11]      Reps.
  Population (2020) [10]            mi2  km2 Reps.
0                 689545             68  176  1[C]

In [43]:
tableData[4].to_csv("state.csv")

In [44]:
my_table=doc.find("table", class_="wikitable sortable plainrowheaders")


th_tags = my_table.find_all('th')
names = []
for elem in th_tags:
  #finding the < a > tag
    a_links = elem.find_all("a")
    #getting the text inside the < a > tag
    for i in a_links:
        names.append(i.string)
print(names)

['postal abbreviation', None, 'Capital', 'Acquired', None, None, None, None, None, 'Reps.', 'American Samoa', 'Guam', 'Northern Mariana Islands', 'Puerto Rico', 'U.S. Virgin Islands']

In [45]:
final_list = names[9: ]
states = []
for str in final_list:
    if len(str) > 3:
        states.append(str)
print(states)

['Reps.', 'American Samoa', 'Guam', 'Northern Mariana Islands', 'Puerto Rico', 'U.S. Virgin Islands']

In [1]:
def sayHello():
  print("Hello from us")

In [12]:
import threading
class OurThread(threading.Thread):
  def __init__(self,name):
    super().__init__()
    self.name=name
  def run(self):
    sayHello()
t1 = OurThread("t1")
t2 = OurThread("t2")
t1.start()
t2.start()

Hello from us
Hello from us

In [3]:
t1= threading.Thread(target=sayHello)
t2= threading.Thread(target=sayHello)
t1.start()
t2.start()

Hello from us
Hello from us

In [4]:
import concurrent.futures
pool=concurrent.futures.ThreadPoolExecutor(max_workers=2)
pool.submit(sayHello)
pool.submit(sayHello)
pool.submit(sayHello)
pool.shutdown(wait=True)

Hello from us
Hello from us
Hello from us

In [17]:
import threading
import time
lock=threading.Lock()
counter=0
def increment():
    print("Inside thread",threading.current_thread().getName())
    lock.acquire()
    try:
      global counter
      print("Inside increment",threading.current_thread().getName())
      time.sleep(3)
      counter+=1
      print(counter)
    except Exception as e:
      print("Exception",e)
    finally:
      lock.release()
import concurrent.futures
pool=concurrent.futures.ThreadPoolExecutor(max_workers=2)
pool.submit(increment)
pool.submit(increment)
pool.submit(increment)
pool.submit(increment)
pool.shutdown(wait=True)

/tmp/ipython-input-17-1748322746.py:6: DeprecationWarning: getName() is deprecated, get the name attribute instead
  print("Inside thread",threading.current_thread().getName())
/tmp/ipython-input-17-1748322746.py:10: DeprecationWarning: getName() is deprecated, get the name attribute instead
  print("Inside increment",threading.current_thread().getName())

Inside thread ThreadPoolExecutor-8_0
Inside increment ThreadPoolExecutor-8_0
Inside thread ThreadPoolExecutor-8_1
1
Inside thread ThreadPoolExecutor-8_0
Inside increment ThreadPoolExecutor-8_1
2
Inside thread ThreadPoolExecutor-8_1
Inside increment ThreadPoolExecutor-8_1
3
Inside increment ThreadPoolExecutor-8_0
4

In [18]:
import time

In [14]:
time.sleep(1000)

KeyboardInterrupt:

In [15]:
help(time.sleep)

Help on built-in function sleep in module time:

sleep(...)
    sleep(seconds)

    Delay execution for a given number of seconds.  The argument may be
    a floating point number for subsecond precision.

In [16]:
time.sleep(5)