In [ ]:
#Api ==rest ful services

In [ ]:
pip install flask

In [ ]:
from flask import Flask,request

app =Flask(__name__)

@app.route("/")
def hello():
    return "Hello from Flask"
    
@app.route("/wc")
def wc():
    return "Welcome to the world of Api"

@app.route("/welcome/<user>")#user is path parameter
def welcome(user):
    return "Welcome "+user
    
@app.route("/display",defaults={"user":"Raja","age":66})
@app.route("/display/<user>/<age>")
def display(user,age):
    return "Hi "+user+" ur age is "+str(age)
@app.route("/add/<int:n1>/<int:n2>")
def add(n1,n2):
    return str(n1+n2)
@app.route("/queryadd")
def queryAdd():
    n1=request.args.get("n1",type=int)
    n2=request.args.get("n2",type=int)
    return str(n1+n2)

app.run()

In [ ]:
from flask import Flask,request

app =Flask(__name__)

@app.route("/calculate")
def calculate():
    n1=request.args.get("n1",type=int)
    n2=request.args.get("n2",type=int)
    operator=request.args.get("op")
    if operator == "+":
        return str(n1+n2)
    elif operator == "-":
        return str(n1-n2)
    elif operator == "*":
        return str(n1*n2)
    elif operator =="/":
        return str(n1/n2)
    else:
        return "Something wrong"

app.run()

In [ ]:
from flask import Flask,request,jsonify

app =Flask(__name__)
@app.route("/add",methods=["POST"])
def posteg():
    data=request.json
    print(data)
    return jsonify({"res":int(data.get("n1"))+int(data.get("n2"))})
app.run()

In [ ]:
from flask import Flask,request,jsonify

app =Flask(__name__)

empList={}

@app.route("/emp",methods=["GET"])
def getemps():
    params=request.args
    if "empid" in params:
        return jsonify(empList.get(params.get("empid")))
    else:
        return jsonify(empList)
@app.route("/add",methods=["POST"])
def addEmp():
    data=request.json
    empid=data.get("empid")
    empList[empid]=data
    return jsonify({"success":True})
    
@app.route("/update/<empid>",methods=["PUT"])
def updateEmp(empid):
    empid =int(empid)
    if empid in empList:
        empList[empid]=request.json
        return jsonify({"success":True})
    else:
        return jsonify({"success":False})
 
@app.route("/delete/<empid>",methods=["DELETE"])
def deleteEmp(empid):
    empid =int(empid)
    if empid in empList:
        del empList[empid]
        return  jsonify({"success":True})
    else:
         return jsonify({"success":False})
app.run()

In [ ]:
import sqlite3

In [ ]:
conn = sqlite3.connect("test.db")
conn.execute(""" 
create table iris_new( sepallength text,	sepalwidth text,	petallength text,	petalwidth text,	variety text)
""")
conn.close()

In [ ]:
import sqlite3
conn = sqlite3.connect("test.db")
cursor =conn.cursor()
irisData =[("10","10","5","5","sunflower"),("30","10","5","5","rose")]
sqlinsert="insert into iris_new(sepallength,sepalwidth,petallength,petalwidth,variety) values(?,?,?,?,?)"
cursor.executemany(sqlinsert,irisData)
conn.commit()
conn.close()

In [ ]:
import sqlite3
conn = sqlite3.connect("test.db")
conn.row_factory=sqlite3.Row
cursor =conn.cursor()

cursor.execute("select * from iris_new")
rows=cursor.fetchall()
for row in rows:
    print(dict(row))
conn.close()

In [ ]:
import sqlite3
conn = sqlite3.connect("test.db")
conn.row_factory=sqlite3.Row
cursor =conn.cursor()

cursor.execute("select * from iris_new where sepalwidth=?",(10,))
rows=cursor.fetchall()
for row in rows:
    print(dict(row))
conn.close()

In [ ]:
import sqlite3
from flask import Flask,request,jsonify

app =Flask(__name__)
@app.route("/add",methods=["POST"])
def addiris():
    try:
        conn = sqlite3.connect("test.db")
        conn.row_factory=sqlite3.Row
        data=request.json
        cursor =conn.cursor()
        irisData=[data]
        cursor.executemany(sqlinsert,irisData)
        conn.commit()
        conn.close()
        return jsonify({"success":True})
    except Exception as e:
        print("Exception",e)
        return jsonify({"success":False})

@app.route("/iris")
def getAll():
    try:
        conn = sqlite3.connect("test.db")
        conn.row_factory=sqlite3.Row
        dataLst=[]
        cursor =conn.cursor()
        cursor.execute("select * from iris_new")
        rows=cursor.fetchall()
        for row in rows:
            dataLst.append(dict(row))
         conn.close()
        return jsonify(dataLst)
    except Exception as e:
        print("Exception",e)
        return jsonify({"success":False})
app.run()

In [ ]:
pip install mysql-connector-python

In [ ]:
import mysql.connector

In [ ]:
config={"user":"sample","password":"sample","host":"127.0.0.1","database":"jpmc","port":3306}
try:
    conn=mysql.connector.connect(**config)
    cursor=conn.cursor()
    sql="insert into emp(id,name) values(%s,%s)"
    cursor.executemany(sql,[(1,"Vishwa"),(2,"Ravi")])
    conn.commit()
except Exception as e:
    print(e)

In [ ]:
config={"user":"sample","password":"sample","host":"127.0.0.1","database":"jpmc","port":3306}
try:
    conn=mysql.connector.connect(**config)
    cursor=conn.cursor(dictionary=True)
    sql="select * from emp"
    cursor.execute(sql)
    results=cursor.fetchall()
    for row in results:
        print(row)
except Exception as e:
    print(e)

In [ ]:
from flask import Flask,request,jsonify

In [ ]:
app=Flask(__name__)

In [ ]:
from flask import Flask,request,jsonify
app=Flask(__name__)
@app.route("/emps")
def allemp():
    emps =[]
    config={"user":"sample","password":"sample","host":"127.0.0.1","database":"jpmc","port":3306}
    conn=None
    try:
        conn=mysql.connector.connect(**config)
        cursor=conn.cursor(dictionary=True)
        sql="select * from emp"
        cursor.execute(sql)
        results=cursor.fetchall()
        for row in results:
            emps.append(row)
    except Exception as e:
        print(e)
    finally:
        if conn!=None:
            conn.close()
    return emps

@app.route("/add",methods=["POST"])
def add():
    added ={}
    config={"user":"sample","password":"sample","host":"127.0.0.1","database":"jpmc","port":3306}
    conn=None
    try:
        data=request.json
        conn=mysql.connector.connect(**config)
        cursor=conn.cursor()
        sql="insert into emp(id,name) values(%s,%s)"
        cursor.execute(sql,(data.get("id"),data.get("name")))
        conn.commit()
        added["success"]=True
    except Exception as e:
        print(e)
        added["success"]=False

    finally:
        if conn!=None:
            conn.close()
    return added
app.run()

In [ ]:
#sqlalchemy --ORM

In [ ]:
pip install sqlalchemy pymysql

In [ ]:
from sqlalchemy import create_engine,Column,Integer,String,MetaData,Table
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

In [ ]:
url="mysql+pymysql://sample:sample@localhost/jpmc"
enginee=create_engine(url)
Session=sessionmaker(bind=enginee)
session=Session()
Base=declarative_base()

In [ ]:
class Student(Base):
    __tablename__="student"
    id=Column(Integer,primary_key=True)
    name=Column(String(50),nullable=False,)
    age=Column(Integer)

    def __repr__(self):
        return ("id {} name {} age {}".format(self.id,self.name,self.age))

In [ ]:
Base.metadata.create_all(enginee)

In [ ]:
s1=Student(id=1,name="Rahul",age=45)
s2=Student(id=2,name="Ravi",age=45)
session.add(s1)
session.add(s2)
session.commit()

In [ ]:
students=session.query(Student).all()
for s in students:
    print(s)

In [ ]:
students=session.query(Student).filter_by(name="Rahul")
for s in students:
    print(s)

In [ ]:
students=session.query(Student).filter(Student.name.like("R%"))
for s in students:
    print(s)

In [ ]:
from sqlalchemy import create_engine,Column,Integer,String,MetaData,Table
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
url="sqlite:///test.db"
enginee=create_engine(url)
Session=sessionmaker(bind=enginee)
session=Session()
Base=declarative_base()
class Student(Base):
    __tablename__="student"
    id=Column(Integer,primary_key=True)
    name=Column(String(50),nullable=False,)
    age=Column(Integer)

    def __repr__(self):
        return ("id {} name {} age {}".format(self.id,self.name,self.age))

Base.metadata.create_all(enginee)

#s1=Student(id=1,name="Rahul",age=45)
#s2=Student(id=2,name="Ravi",age=45)
#session.add(s1)
#session.add(s2)
#session.commit()
students=session.query(Student).all()
for s in students:
    print(s)

In [ ]:
s

In [ ]:
session.delete(s)
session.commit()

In [ ]:
students=session.query(Student).all()
for s in students:
    print(s)

In [ ]:
student=session.query(Student).filter_by(name="Rahul").first()
session.delete(student)
session.commit()

In [1]:
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy import create_engine,Column,Integer,String,MetaData,Table
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
url="sqlite:///test.db"
enginee=create_engine(url)
Session=sessionmaker(bind=enginee)
session=Session()
Base=declarative_base()
class User(Base):
    __tablename__="user_account"
    id=Column(Integer,primary_key=True)
    name=Column(String(50))
    address=relationship("Address",back_populates="user")

    def __repr__(self):
        return str(id)

class Address(Base):
    __tablename__="address"
    id=Column(Integer,primary_key=True)
    email=Column(String(50))
    user_id=Column(Integer,ForeignKey("user_account.id"))
    user=relationship("User",back_populates="address")
    
    def __repr__(self):
        return str(id)
Base.metadata.create_all(enginee)

C:\Users\VISHWA\AppData\Local\Temp\ipykernel_24032\1153002397.py:10: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base=declarative_base()

In [2]:
user=User(id=1,name="Raj")
add1=Address(id=1,email="raj@gmail.com",user=user)
add2=Address(id=2,email="raj1@gmail.com",user=user)
session.add_all([user,add1,add2])
session.commit()

In [4]:
user.address[0].email

'raj@gmail.com'

In [5]:
user.address[1].email

'raj1@gmail.com'

In [6]:
import pandas as pd

In [7]:
usersdf=pd.read_sql("select * from user_account",con=enginee)

In [9]:
usersdf

   id name
0   1  Raj

In [10]:
irisdf=pd.read_sql("select * from iris_new",con=enginee)

In [11]:
irisdf

  sepallength sepalwidth petallength petalwidth    variety
0          10         10           5          5  sunflower
1          30         10           5          5       rose

In [12]:
iris=pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")

In [13]:
iris.to_sql(name="new_iris",con=enginee,if_exists="replace",index=False)

150

In [14]:
iris_new=pd.read_sql("select * from new_iris",con=enginee)

In [15]:
iris_new

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [16]:
cars=pd.read_csv("https://gist.githubusercontent.com/noamross/e5d3e859aa0c794be10b/raw/b999fb4425b54c63cab088c0ce2c0d6ce961a563/cars.csv")

In [17]:
cars.to_sql(name="cars",con=enginee,if_exists="replace",index=False)

32

In [19]:
cars_new=pd.read_sql("select * from cars",con=enginee)

In [20]:
cars_new

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2