In [2]:
#Any function which I create within a class will always have self
class Sample:
  #We have to create constructor
  def __init__(self,n1):
    self.n1=n1
  def display(self):
    print("n1",self.n1)

In [3]:
s1 = Sample(20)#This will call init
print(s1.n1)
s1.display()

20
n1 20

In [4]:
s2 = Sample(34)
s2.display()

n1 34

In [6]:
class Emp:
    def __init__(self,id,name,salary):
        self.id=id
        self.name=name
        self.salary=salary
    def display(self):
        print("ID {} NAME {} SALARY {}".format(self.id,self.name,self.salary))

In [8]:
e1 = Emp(1,"Raj",1000)
e1.display()

ID 1 NAME Raj SALARY 1000

In [9]:
e1.id

1

In [10]:
e1.name

'Raj'

In [11]:
e1.salary

1000

In [12]:
e1.age =55#dynamic attributes are possible
#These attriutes will be available only in this object

In [13]:
e2 =Emp(2,"Arjun",5000)

In [14]:
e2.display()

ID 2 NAME Arjun SALARY 5000

In [15]:
e2.age

AttributeError: 'Emp' object has no attribute 'age'

In [22]:
class NonDynamic:
    __slots__=["p1","p2"] #indicates attributes allowed within object
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def display(self):
        print("p1",self.p1,"p2",self.p2)

In [25]:
n1=NonDynamic(22,33)
n1.display()

p1 22 p2 33

In [26]:
n1.p3=100 #This will cause error beacuse __slots__ are defined

AttributeError: 'NonDynamic' object has no attribute 'p3'

In [27]:
class Calculator:
    def __init__(self,n1,n2):
        self.n1=n1
        self.n2=n2
        self.res=0
    def add(self):
        self.res = self.n1+self.n2
    def sub(self):
        self.res=self.n1-self.n2
    def mul(self):
        self.res=self.n1*self.n2
    def div(self):
        self.res=self.n1/self.n2

In [28]:
c1= Calculator(10,2)
c1.add()
print(c1.res)

12

In [29]:
class Power:
    #Within python we have concept of default values
    def __init__(self,x,y=1):
        self.x =x
        self.y=y
    def calc(self):
        return self.x**self.y

In [30]:
p1 = Power(2)
print(p1.calc())

2

In [32]:
p2 = Power(2,3)
print(p2.calc())

8

In [44]:
class Student:
    def __init__(self,rollNo,name):
        self.rollNo=rollNo
        self.name=name
    def __str__(self): # equialent of toString in java
        return "Roll No {} Name {}".format(self.rollNo,self.name)

In [45]:
s1 =Student(1,"Raj")

In [46]:
print(s1)

Roll No 1 Name Raj

In [47]:
str(s1)

'Roll No 1 Name Raj'

In [48]:
s1.__dict__ #Inbuild objects in form dictionary

{'rollNo': 1, 'name': 'Raj'}

In [49]:
#Inheritance
#Parent child
#Few form multiple inheritance

In [50]:
class Parent1:
    def __init__(self,p1):
        self.p1=p1
    def displayP1(self):
        print("p1 from Parent1",self.p1)

In [56]:
class Child1(Parent1):#Inheritance
    def __init__(self,p1,p2):
        Parent1.__init__(self,p1)#Calling the base class constructor
        self.p2=p2

In [57]:
c1 = Child1(22,33)

In [58]:
c1.p1

22

In [59]:
c1.p2

33

In [60]:
c1.displayP1()

p1 from Parent1 22

In [ ]:
#Multiple Inheritance

#P1 display
#P2 display
#C -p1-p2--display

In [62]:
class P1:
    def __init__(self,n1):
        self.n1=n1
    def display(self):
        print("From P1 n1=",self.n1)

In [63]:
class P2:
    def __init__(self,n2):
        self.n2=n2
    def display(self):
        print("From P2 n2=",self.n2)

In [64]:
class Child2(P1,P2):#In the case of conflict, resolves sequence of inheritance
    def __init__(self,n1,n2):
        P1.__init__(self,n1)
        P2.__init__(self,n2)

In [65]:
c2 =Child2(22,33)

In [66]:
c2.display()

From P1 n1= 22

In [67]:
class Child3(P2,P1):
    def __init__(self,n1,n2):
        P1.__init__(self,n1)
        P2.__init__(self,n2)

In [68]:
c3 =Child3(33,44)

In [69]:
c3.display()

From P2 n2= 44

In [70]:
#Abstract class is a class which cannot be instantinated

In [71]:
from abc import ABC,abstractmethod

In [72]:
class Shape(ABC):#Inheriting from ABC indicates abstract 
    @abstractmethod#We are saying that class which inherits has to give body..
    def area(self):
        pass #equivalent of no body
    def display(self):
        print("I am in Shape")

In [79]:
class Circle(Shape):
    def __init__(self,radius):
        self.radius =radius
    def area(self):
        return 3.14*self.radius*self.radius
    def display(self):
        print("I am circle")

In [80]:
c1 = Circle(3)

In [81]:
c1.display()

I am circle

In [76]:
c1.area()

28.259999999999998

In [77]:
class Square(Shape):
    def __init__(self,side):
        self.side=side

In [78]:
s1 =Square(22)

TypeError: Can't instantiate abstract class Square with abstract method area

In [82]:
from collections import namedtuple
#using named tuple u can eaily create classes on fly

In [84]:
Point =namedtuple("Point",["x","y"])

In [88]:
p1 = Point(10,20)

In [89]:
p1.x

10

In [90]:
p1.y

20

In [91]:
pip install python-interface

Collecting python-interface
  Downloading python-interface-1.6.1.tar.gz (19 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: six in c:\users\vishwa\appdata\roaming\python\python311\site-packages (from python-interface) (1.17.0)
Building wheels for collected packages: python-interface
  Building wheel for python-interface (pyproject.toml): started
  Building wheel for python-interface (pyproject.toml): finished with status 'done'
  Created wheel for python-interface: filename=python_interface-1.6.1-py3-none-any.whl size=23322 sha256=a48f7f8250d2df76754f8b696d052b9d6ae90e696d5b2f5efc4a8b91a19fcbe0
  Stored in directory: c:\users\vishwa\appdata\local\pip\cache\wheels\21\0b\9e\f35e76c1533933fdc351488b1bcdf29b10b0df7589f5971fb9
Successfully built python-interface
Installing collected packages: python-interface
Successfully installed python-interface-1.6.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [92]:
from interface import implements,Interface

In [93]:
class CustomInterface(Interface):
    def m1(self):
        pass
    def m2(self):
        pass

In [94]:
class CustomImplementor(implements(CustomInterface)):
    def m1(self):
        print("m1")
    def m2(self):
        print("m2")

In [97]:
#Operator overloading
class Complex:
    def __init__(self,real,img):
        self.real=real
        self.img = img
    def __str__(self):
        return "real {} img {}".format(self.real,self.img)
    def add(self,other):
        r1 =self.real+other.real
        i1 =self.img+other.img
        return Complex(r1,i1)
    def __add__(self,other):# implementing + operator
        r1 =self.real+other.real
        i1 =self.img+other.img
        return Complex(r1,i1)

In [98]:
c1 =Complex(22,10)
c2 = Complex(20,40)
c3=c1.add(c2)
print(c3)
c4 =c1 +c2 #Example of operator overloading
print(c4)

real 42 img 50
real 42 img 50

In [104]:
class Point:
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def __lt__(self,other):
        print("less than is called")
        m1 =self.x*self.x+self.y*self.y
        m2 = other.x*other.x+other.y*other.y
        return m1 < m2
    def __le__(self,other):
        print("less than/equal is called")
        m1 =self.x*self.x+self.y*self.y
        m2 = other.x*other.x+other.y*other.y
        return m1 <= m2    
    def __gt__(self,other):
        print("greater than is called")
        m1 =self.x*self.x+self.y*self.y
        m2 = other.x*other.x+other.y*other.y
        return m1 > m2
    def __ge__(self,other):
        print("greater than/equal is called")
        m1 =self.x*self.x+self.y*self.y
        m2 = other.x*other.x+other.y*other.y
        return m1 >= m2
    def __eq__(self,other):
        print("equal  is called")
        m1 =self.x*self.x+self.y*self.y
        m2 = other.x*other.x+other.y*other.y
        return m1 == m2

In [105]:
p1 =Point(1,2)
p2=Point(1,3)

In [106]:
p1 < p2

less than is called

True

In [107]:
p1 > p2

greater than is called

False

In [108]:
p1 <= p2

less than/equal is called

True

In [109]:
p1 >=p2

greater than/equal is called

False

In [110]:
p1==p2

equal  is called

False

In [115]:
class ClassLevel:
    counter =0 #Any variable created above init is class level
    #They can be accessed by using classname
    #No need create objects for accessing them
    def __init__(self,n1):
        self.n1=n1
        ClassLevel.counter=ClassLevel.counter+1

In [112]:
c1 = ClassLevel(10)

In [113]:
c2 =ClassLevel(20)

In [114]:
ClassLevel.counter

2

In [116]:
class CalculatorUtil:
    @staticmethod #these are methods which can be called by using classname, they need no object
    def add(a,b):
        return a+b
    @staticmethod
    def sub(a,b):
        return a-b

In [117]:
CalculatorUtil.add(22,33)

55

In [ ]:
#Meta programming
#Python
#Functions can be created within functions
#Functions can be passed as arguments to functions
#Functions can be returned as result

In [118]:
def outer():
    print("Within outer")
    def inner():#Function can be created within function
        print("Within inner")
    inner()

In [119]:
outer()

Within outer
Within inner

In [125]:
def outer1():
    print("Within outer1")
    def inner():#Function can be created within function
        print("Within inner")
    return inner #Functions can be returned from nother function

In [126]:
f1 = outer1()#Storing result function in f1

Within outer1

In [127]:
f1()

Within inner

In [128]:
outer1()()

Within outer1
Within inner

In [131]:
def outer2(param1):#Function can be passed as an argument
    print("Within outer before calling param")
    param1()
    print("Within outer after calling param")

In [132]:
def hello():
    print("Hello from us")

In [133]:
outer2(hello)

Within outer before calling param
Hello from us
Within outer after calling param

In [135]:
def outer3(param1):
    print("Inside outer3")
    def inner():
        print("Inside inner")
        print("Before calling param1")
        param1()
        print("After calling param1")
        
    return inner

In [136]:
f2 = outer3(hello)

Inside outer3

In [137]:
f2()

Inside inner
Before calling param1
Hello from us
After calling param1

In [138]:
@outer3#This is equivalent of saying outer3(hello2)
def hello2():
    print("Hello World from 2")

Inside outer3

In [139]:
hello2()

Inside inner
Before calling param1
Hello World from 2
After calling param1

In [140]:
def sum(*values):#Variable arguments are done using *
    res =0
    for element in values:
        res=res+element
    return res

In [141]:
r1 =sum(10,20)
print(r1)

30

In [142]:
r2=sum(10,20,30)
print(r2)

60

In [143]:
def process(**data):
    for k,v in data.items():
        print(k,v)

In [144]:
process(uk="united kingdom",usa="united states")

uk united kingdom
usa united states

In [146]:
process(**{"uk":"united kingdom","usa":"United states"})

uk united kingdom
usa United states

In [ ]:
#Python access specifier
#They are more of an indication
#private __
#public 
#protected _

In [147]:
class PrivateVariables:
    def __init__(self,p1):
        self.__p1=p1
    def display(self):
        print("Private",self.__p1)

In [148]:
obj1=PrivateVariables(10)

In [149]:
obj1.display()

Private 10

In [150]:
obj1.__p1

AttributeError: 'PrivateVariables' object has no attribute '__p1'

In [151]:
obj1.__dict__

{'_PrivateVariables__p1': 10}

In [152]:
obj1._PrivateVariables__p1 #Private variables can be accessed by classname and variable name

10

In [153]:
class Emp:
    def __init__(self,id,name,salary):
        self.id=id
        self.name=name
        self.salary=salary
    def display(self):
        print("ID {} NAME {} SALARY {}".format(self.id,self.name,self.salary))

In [154]:
e1 = Emp(1,"Ram",5000)

In [155]:
import pickle

In [159]:
with open("C://t//e1.ser","wb") as op:
    pickle.dump(e1,op)

In [160]:
with open("C://t//e1.ser","rb") as ip:
    e2= pickle.load(ip)
    e2.display()

ID 1 NAME Ram SALARY 5000

In [161]:
#Reading and writing
#Text/CSV/JSON/XML

In [ ]:
#TEXT
#open file
#read/file
#close

In [162]:
ip = open("C://t//test//sample.txt","w")
ip.write("Hello world\n")
ip.write("Files")
ip.close()

In [ ]:
with open("C://t//test//sample.txt","a") as ip:#opening files with is good beacusethey are autoclose
    ip.write("Hello world\n")
    ip.write("Files")

In [164]:
#read entire file in one go
with open("C://t//test//sample.txt","r") as op:
    content=op.read()
    print(content)

Hello world
Files

In [165]:
with open("C://t//test//sample.txt","r") as op:
    for line in op:#This apprach is more preferred beacuse we read line by line
        print(line)

Hello world

Files

In [166]:
#CSV ----csv
#csv ---list of dictinaries to csv and vice versa

In [169]:
import csv
dataLst=[{"id":1,"name":"Raju"},{"id":2,"name":"Alex"}]
with open("C://t//test//emp.csv","w",newline='') as op:
    dw=csv.DictWriter(op,fieldnames=["id","name"],)
    dw.writeheader()
    dw.writerows(dataLst)

In [170]:
with open("C://t//test//emp.csv","r") as ip:
    dr =csv.DictReader(ip)
    for row in dr:
        print(row)

{'id': '1', 'name': 'Raju'}
{'id': '2', 'name': 'Alex'}

In [172]:
import json
dataLst=[{"id":1,"name":"Raju"},{"id":2,"name":"Alex"}]
with open("C://t//test//sample.json","w") as op:
    json.dump(dataLst,op)

In [173]:
with open("C://t//test//sample.json","r") as ip:
    dataLoaded = json.load(ip)
    print(dataLoaded)

[{'id': 1, 'name': 'Raju'}, {'id': 2, 'name': 'Alex'}]

In [ ]:
#XML ---
#Tag
#<root> <child>.....</child></root>
#Tag Element

In [174]:
pip install lxml

Requirement already satisfied: lxml in c:\python311\lib\site-packages (5.4.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [175]:
from lxml import etree
root =etree.Element("users")
user1=etree.Element("user")
name1=etree.Element("name")
user1.append(name1)
name1.text="Raj"
user2=etree.Element("user")
name2=etree.Element("name")
user2.append(name2)
name2.text="Raju"
root.append(user1)
root.append(user2)
xmlString = etree.tostring(root,pretty_print=True).decode("utf-8")
with open("C://t//test//sample.xml","w") as  op:
    op.write(xmlString)

In [176]:
with open("C://t//test//sample.xml","r") as ip:
    xmlData =etree.parse(ip)
    root=xmlData.getroot()
    for user in root.findall("user"):
        print(user.find("name").text)

Raj
Raju

In [177]:
pip install requests

Requirement already satisfied: requests in c:\users\vishwa\appdata\roaming\python\python311\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python311\lib\site-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\python311\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python311\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\vishwa\appdata\roaming\python\python311\site-packages (from requests) (2024.12.14)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [179]:
import requests
proxies = {
    'http': 'http://your_http_proxy_ip:port',
    'https': 'http://your_https_proxy_ip:port', # Use 'http://' for HTTPS proxies if they handle both
}

googledata=requests.get("http://www.google.com",proxies=proxies).text
print(googledata)

<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en-IN"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="JJQ8gygz3frGy-J3sT2qjA">(function(){var _g={kEI:'nEGLaO3VJ46d5OUPyIOI-QU',kEXPI:'0,202854,2,3497408,685,435,538661,48791,30022,16105,78218,266578,290044,11106,5219174,12,11389,563,36812080,25340895,26054,14110,65174,6751,23879,9139,4599,328,6225,64165,15048,8206,3292,4134,30379,696,155,27483,29247,24964,353,4099,14781,5870,1888,1970,3856,5774,21643,5968,3050,2,4212,9260,3261,2990,35,3420,2115,749,2674,210,7735,12108,2625,1081,1977,3604,13805,3967,2731,623,1225,2,11,4569,8838,633,646,4222,4,4,5746,3,1470,3858,1658,96,4838,1,3459,2,1574,4,1,2,2,2,2136,463,7,488,890,600,1033,946,6,626,4187,672,982,3,1061,13,6,3,7674,683,251,979,733,103,4,1,320,841,2,347,2920,990,670,27,3,113,2991,1393,7150,3,2,2,2,1331,687,2758,1476,4,106,1481,2,2,1505,2714,691,3196,438,927,729,5,149,18,2161,1208,72,53,278,259,2,1,1379,32,104,3070,483,338,1973,2,195,476,10,3,705,976,1022,112,2,99,3,433,746,66,5,1,682,127,878,21,775,5,1410,312,18,6,977,284,573,1183,2194,251,1138,482,9,1,302,1729,3,663,507,31,2,246,4,637,1364,142,1032,396,526,42,1,2,33,708,133,25,495,1134,3,1048,3,12,1,57,1190,147,426,156,1445,426,448,134,12,51,107,19,869,3,2058,78,15,780,362,108,455,31,1367,1023,96,615,8,4,392,208,927,4,148,602,3,2,2,2,770,58,50,117,501,21,159,4,4,349,255,138,24,247,75,22,142,203,46,237,124,117,1845,160,105,604,222,353,201,3,595,174,366,7,5,1104,569,25,29,257,1,232,18,1,3,179,410,822,66,35,225,227,2,663,174,40,112,8,246,185,7,4,53,546,68,484,1215,273,50,6,642,158,713,23,11,244,36,602,537,1272,799,1199,533,21199118,5,2253,739,4,2700,260,3,1308,1929,5254,2,1558,3,2165,281,3,1297,3,454,3,170,60,41,3838,149,200,1,3,432,50,187,374,129,309,940,8488410',kBL:'EA14',kOPI:89978449};(function(){var a;((a=window.google)==null?0:a.stvsc)?google.kEI=_g.kEI:window.google=_g;}).call(this);})();(function(){google.sn='webhp';google.kHL='en-IN';})();(function(){
var g=this||self;function k(){return window.google&&window.google.kOPI||null};var l,m=[];function n(a){for(var b;a&&(!a.getAttribute||!(b=a.getAttribute("eid")));)a=a.parentNode;return b||l}function p(a){for(var b=null;a&&(!a.getAttribute||!(b=a.getAttribute("leid")));)a=a.parentNode;return b}function q(a){/^http:/i.test(a)&&window.location.protocol==="https:"&&(google.ml&&google.ml(Error("a"),!1,{src:a,glmm:1}),a="");return a}
function r(a,b,d,c,h){var e="";b.search("&ei=")===-1&&(e="&ei="+n(c),b.search("&lei=")===-1&&(c=p(c))&&(e+="&lei="+c));var f=b.search("&cshid=")===-1&&a!=="slh";c="&zx="+Date.now().toString();g._cshid&&f&&(c+="&cshid="+g._cshid);(d=d())&&(c+="&opi="+d);return"/"+(h||"gen_204")+"?atyp=i&ct="+String(a)+"&cad="+(b+e+c)};l=google.kEI;google.getEI=n;google.getLEI=p;google.ml=function(){return null};google.log=function(a,b,d,c,h,e){e=e===void 0?k:e;d||(d=r(a,b,e,c,h));if(d=q(d)){a=new Image;var f=m.length;m[f]=a;a.onerror=a.onload=a.onabort=function(){delete m[f]};a.src=d}};google.logUrl=function(a,b){b=b===void 0?k:b;return r("",a,b)};}).call(this);(function(){google.y={};google.sy={};function e(a,b,c){if(a)var d=a.id;else{do d=Math.random();while(c[d])}c[d]=[a,b]}var f;(f=google).x||(f.x=function(a,b){e(a,b,google.y)});var g;(g=google).sx||(g.sx=function(a,b){e(a,b,google.sy)});google.lm=[];var h;(h=google).plm||(h.plm=function(a){google.lm.push.apply(google.lm,a)});google.lq=[];var k;(k=google).load||(k.load=function(a,b,c){google.lq.push([[a],b,c])});var l;(l=google).loadAll||(l.loadAll=function(a,b){google.lq.push([a,b])});google.bx=!1;var m;(m=google).lx||(m.lx=function(){});var n=[],p;(p=google).fce||(p.fce=function(a,b,c,d){n.push([a,b,c,d])});google.qce=n;google.adl=[];}).call(this);google.f={};(function(){
document.documentElement.addEventListener("submit",function(b){var a;if(a=b.target){var c=a.getAttribute("data-submitfalse");a=c==="1"||c==="q"&&!a.elements.q.value?!0:!1}else a=!1;a&&(b.preventDefault(),b.stopPropagation())},!0);document.documentElement.addEventListener("click",function(b){var a;a:{for(a=b.target;a&&a!==document.documentElement;a=a.parentElement)if(a.tagName==="A"){a=a.getAttribute("data-nohref")==="1";break a}a=!1}a&&b.preventDefault()},!0);}).call(this);</script><style>#gbar,#guser{font-size:13px;padding-top:1px !important;}#gbar{height:22px}#guser{padding-bottom:7px !important;text-align:right}.gbh,.gbd{border-top:1px solid #c9d7f1;font-size:1px}.gbh{height:0;position:absolute;top:24px;width:100%}@media all{.gb1{height:22px;margin-right:.5em;vertical-align:top}#gbar{float:left}}a.gb1,a.gb4{text-decoration:underline !important}a.gb1,a.gb4{color:#00c !important}.gbi .gb4{color:#dd8e27 !important}.gbf .gb4{color:#900 !important}
</style><style>body,td,a,p,.h{font-family:sans-serif}body{margin:0;overflow-y:scroll}#gog{padding:3px 8px 0}td{line-height:.8em}.gac_m td{line-height:17px}form{margin-bottom:20px}.h{color:#1967d2}em{font-weight:bold;font-style:normal}.lst{height:25px;width:496px}.gsfi,.lst{font:18px sans-serif}.gsfs{font:17px sans-serif}.ds{display:inline-box;display:inline-block;margin:3px 0 4px;margin-left:4px}input{font-family:inherit}body{background:#fff;color:#1f1f1f}a{color:#681da8;text-decoration:none}a:hover,a:active{text-decoration:underline}.fl a{color:#1967d2}a:visited{color:#681da8}.sblc{padding-top:5px}.sblc a{display:block;margin:2px 0;margin-left:13px;font-size:11px}.lsbb{background:#f8f9fa;border:solid 1px;border-color:#dadce0 #70757a #70757a #dadce0;height:30px}.lsbb{display:block}#WqQANb a{display:inline-block;margin:0 12px}.lsb{background:url(/images/nav_logo229.png) 0 -261px repeat-x;color:#1f1f1f;border:none;cursor:pointer;height:30px;margin:0;outline:0;font:15px sans-serif;vertical-align:top}.lsb:active{background:#dadce0}.lst:focus{outline:none}</style><script nonce="JJQ8gygz3frGy-J3sT2qjA">(function(){window.google.erd={jsr:1,bv:2262,de:true,dpf:'iAB35yJF5jf9y01IQ6brg5J9omafyL2YKXIyd3qe-Vw'};
var g=this||self;var k,l=(k=g.mei)!=null?k:1,m,p=(m=g.diel)!=null?m:0,q,r=(q=g.sdo)!=null?q:!0,t=0,u,w=google.erd,x=w.jsr;google.ml=function(a,b,d,n,e){e=e===void 0?2:e;b&&(u=a&&a.message);d===void 0&&(d={});d.cad="ple_"+google.ple+".aple_"+google.aple;if(google.dl)return google.dl(a,e,d,!0),null;b=d;if(x<0){window.console&&console.error(a,b);if(x===-2)throw a;b=!1}else b=!a||!a.message||a.message==="Error loading script"||t>=l&&!n?!1:!0;if(!b)return null;t++;d=d||{};b=encodeURIComponent;var c="/gen_204?atyp=i&ei="+b(google.kEI);google.kEXPI&&(c+="&jexpid="+b(google.kEXPI));c+="&srcpg="+b(google.sn)+"&jsr="+b(w.jsr)+
"&bver="+b(w.bv);w.dpf&&(c+="&dpf="+b(w.dpf));var f=a.lineNumber;f!==void 0&&(c+="&line="+f);var h=a.fileName;h&&(h.indexOf("-extension:/")>0&&(e=3),c+="&script="+b(h),f&&h===window.location.href&&(f=document.documentElement.outerHTML.split("\n")[f],c+="&cad="+b(f?f.substring(0,300):"No script found.")));google.ple&&google.ple===1&&(e=2);c+="&jsel="+e;for(var v in d)c+="&",c+=b(v),c+="=",c+=b(d[v]);c=c+"&emsg="+b(a.name+": "+a.message);c=c+"&jsst="+b(a.stack||"N/A");c.length>=12288&&(c=c.substring(0,12288));a=c;n||google.log(0,"",a);return a};window.onerror=function(a,b,d,n,e){u!==a&&(a=e instanceof Error?e:Error(a),d===void 0||"lineNumber"in a||(a.lineNumber=d),b===void 0||"fileName"in a||(a.fileName=b),google.ml(a,!1,void 0,!1,a.name==="SyntaxError"||a.message.substring(0,11)==="SyntaxError"||a.message.indexOf("Script error")!==-1?3:p));u=null;r&&t>=l&&(window.onerror=null)};})();</script></head><body bgcolor="#fff"><script nonce="JJQ8gygz3frGy-J3sT2qjA">(function(){var src='/images/nav_logo229.png';var iesg=false;document.body.onload = function(){window.n && window.n();if (document.images){new Image().src=src;}
if (!iesg){document.f&&document.f.q.focus();document.gbqf&&document.gbqf.q.focus();}
}
})();</script><div id="mngb"><div id=gbar><nobr><b class=gb1>Search</b> <a class=gb1 href="https://www.google.com/imghp?hl=en&tab=wi">Images</a> <a class=gb1 href="http://maps.google.co.in/maps?hl=en&tab=wl">Maps</a> <a class=gb1 href="https://play.google.com/?hl=en&tab=w8">Play</a> <a class=gb1 href="https://www.youtube.com/?tab=w1">YouTube</a> <a class=gb1 href="https://news.google.com/?tab=wn">News</a> <a class=gb1 href="https://mail.google.com/mail/?tab=wm">Gmail</a> <a class=gb1 href="https://drive.google.com/?tab=wo">Drive</a> <a class=gb1 style="text-decoration:none" href="https://www.google.co.in/intl/en/about/products?tab=wh"><u>More</u> &raquo;</a></nobr></div><div id=guser width=100%><nobr><span id=gbn class=gbi></span><span id=gbf class=gbf></span><span id=gbe></span><a href="http://www.google.co.in/history/optout?hl=en" class=gb4>Web History</a> | <a  href="/preferences?hl=en" class=gb4>Settings</a> | <a target=_top id=gb_70 href="https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=http://www.google.com/&ec=GAZAAQ" class=gb4>Sign in</a></nobr></div><div class=gbh style=left:0></div><div class=gbh style=right:0></div></div><center><br clear="all" id="lgpd"><div id="XjhHGf"><img alt="Google" height="92" src="/images/branding/googlelogo/1x/googlelogo_white_background_color_272x92dp.png" style="padding:28px 0 14px" width="272" id="hplogo"><br><br></div><form action="/search" name="f"><table cellpadding="0" cellspacing="0"><tr valign="top"><td width="25%">&nbsp;</td><td align="center" nowrap=""><input name="ie" value="ISO-8859-1" type="hidden"><input value="en-IN" name="hl" type="hidden"><input name="source" type="hidden" value="hp"><input name="biw" type="hidden"><input name="bih" type="hidden"><div class="ds" style="height:32px;margin:4px 0"><input class="lst" style="margin:0;padding:5px 8px 0 6px;vertical-align:top;color:#1f1f1f" autocomplete="off" value="" title="Google Search" maxlength="2048" name="q" size="57"></div><br style="line-height:0"><span class="ds"><span class="lsbb"><input class="lsb" value="Google Search" name="btnG" type="submit"></span></span><span class="ds"><span class="lsbb"><input class="lsb" id="tsuid_nEGLaO3VJ46d5OUPyIOI-QU_1" value="I'm Feeling Lucky" name="btnI" type="submit"><script nonce="JJQ8gygz3frGy-J3sT2qjA">(function(){var id='tsuid_nEGLaO3VJ46d5OUPyIOI-QU_1';document.getElementById(id).onclick = function(){if (this.form.q.value){this.checked = 1;if (this.form.iflsig)this.form.iflsig.disabled = false;}
else top.location='/doodles/';};})();</script><input value="AOw8s4IAAAAAaItPrPCk2k_QEDzxU2JWiVEfpQR171wH" name="iflsig" type="hidden"></span></span></td><td class="fl sblc" align="left" nowrap="" width="25%"><a href="/advanced_search?hl=en-IN&amp;authuser=0">Advanced search</a></td></tr></table><input id="gbv" name="gbv" type="hidden" value="1"><script nonce="JJQ8gygz3frGy-J3sT2qjA">(function(){var a,b="1";if(document&&document.getElementById)if(typeof XMLHttpRequest!="undefined")b="2";else if(typeof ActiveXObject!="undefined"){var c,d,e=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"];for(c=0;d=e[c++];)try{new ActiveXObject(d),b="2"}catch(h){}}a=b;if(a=="2"&&location.search.indexOf("&gbv=2")==-1){var f=google.gbvu,g=document.getElementById("gbv");g&&(g.value=a);f&&window.setTimeout(function(){location.href=f},0)};}).call(this);</script></form><div style="font-size:83%;min-height:3.5em"><br><div id="gws-output-pages-elements-homepage_additional_languages__als"><style>#gws-output-pages-elements-homepage_additional_languages__als{font-size:small;margin-bottom:24px}#SIvCob{color:#545454;display:inline-block;line-height:28px;}#SIvCob a{}.H6sW5{display:inline-block;margin:0 2px;white-space:nowrap}.z4hgWe{display:inline-block;margin:0 2px}</style><div id="SIvCob">Google offered in:  <a href="http://www.google.com/setprefs?sig=0_KTB0Ng_u-I4Y2DdtiQkZhL2BLwQ%3D&amp;hl=hi&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjtk6KP7uaOAxWODrkGHcgBIl8Q2ZgBCAY">&#2361;&#2367;&#2344;&#2381;&#2342;&#2368;</a>    <a href="http://www.google.com/setprefs?sig=0_KTB0Ng_u-I4Y2DdtiQkZhL2BLwQ%3D&amp;hl=bn&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjtk6KP7uaOAxWODrkGHcgBIl8Q2ZgBCAc">&#2476;&#2494;&#2434;&#2482;&#2494;</a>    <a href="http://www.google.com/setprefs?sig=0_KTB0Ng_u-I4Y2DdtiQkZhL2BLwQ%3D&amp;hl=te&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjtk6KP7uaOAxWODrkGHcgBIl8Q2ZgBCAg">&#3108;&#3142;&#3122;&#3137;&#3095;&#3137;</a>    <a href="http://www.google.com/setprefs?sig=0_KTB0Ng_u-I4Y2DdtiQkZhL2BLwQ%3D&amp;hl=mr&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjtk6KP7uaOAxWODrkGHcgBIl8Q2ZgBCAk">&#2350;&#2352;&#2366;&#2336;&#2368;</a>    <a href="http://www.google.com/setprefs?sig=0_KTB0Ng_u-I4Y2DdtiQkZhL2BLwQ%3D&amp;hl=ta&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjtk6KP7uaOAxWODrkGHcgBIl8Q2ZgBCAo">&#2980;&#2990;&#3007;&#2996;&#3021;</a>    <a href="http://www.google.com/setprefs?sig=0_KTB0Ng_u-I4Y2DdtiQkZhL2BLwQ%3D&amp;hl=gu&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjtk6KP7uaOAxWODrkGHcgBIl8Q2ZgBCAs">&#2711;&#2753;&#2716;&#2736;&#2750;&#2724;&#2752;</a>    <a href="http://www.google.com/setprefs?sig=0_KTB0Ng_u-I4Y2DdtiQkZhL2BLwQ%3D&amp;hl=kn&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjtk6KP7uaOAxWODrkGHcgBIl8Q2ZgBCAw">&#3221;&#3240;&#3277;&#3240;&#3233;</a>    <a href="http://www.google.com/setprefs?sig=0_KTB0Ng_u-I4Y2DdtiQkZhL2BLwQ%3D&amp;hl=ml&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjtk6KP7uaOAxWODrkGHcgBIl8Q2ZgBCA0">&#3374;&#3378;&#3375;&#3390;&#3379;&#3330;</a>    <a href="http://www.google.com/setprefs?sig=0_KTB0Ng_u-I4Y2DdtiQkZhL2BLwQ%3D&amp;hl=pa&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjtk6KP7uaOAxWODrkGHcgBIl8Q2ZgBCA4">&#2602;&#2672;&#2588;&#2622;&#2604;&#2624;</a>  </div></div></div><span id="footer"><div style="font-size:10pt"><div style="margin:19px auto;text-align:center" id="WqQANb"><a href="/intl/en/ads/">Advertising</a><a href="http://www.google.co.in/services/">Business Solutions</a><a href="/intl/en/about.html">About Google</a><a href="http://www.google.com/setprefdomain?prefdom=IN&amp;prev=http://www.google.co.in/&amp;sig=K_1MWQ7xFsk71JP8VZnH0k91IM-_E%3D">Google.co.in</a></div></div><p style="font-size:8pt;color:#636363">&copy; 2025 - <a href="/intl/en/policies/privacy/">Privacy</a> - <a href="/intl/en/policies/terms/">Terms</a></p></span></center><script nonce="JJQ8gygz3frGy-J3sT2qjA">(function(){window.google.cdo={height:757,width:1440};(function(){var a=window.innerWidth,b=window.innerHeight;if(!a||!b){var c=window.document,d=c.compatMode=="CSS1Compat"?c.documentElement:c.body;a=d.clientWidth;b=d.clientHeight}if(a&&b&&(a!=google.cdo.width||b!=google.cdo.height)){var e=google,f=e.log,g="/client_204?&atyp=i&biw="+a+"&bih="+b+"&ei="+google.kEI,h="",k=window.google&&window.google.kOPI||null;k&&(h+="&opi="+k);f.call(e,"","",g+h)};}).call(this);})();(function(){google.xjs={basecomb:'/xjs/_/js/k\x3dxjs.hp.en.B7jo0hURfI8.es5.O/ck\x3dxjs.hp.QGw_2SygG64.L.X.O/am\x3dhAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAACAASBC4AAAAACYIAAAAAAAAAEAAAAAAAAAoAAAAKwAAAQgRAABAIAAQQIAgAKASQaAcSAAQIAAoAIBkANQOgAAAAAEEAAEEAAAAgAKAAAASAAAMAAAAAI4AQAAADAAwuOAAAAAAAAAAmIBQAAAAAAAAIhH/d\x3d1/ed\x3d1/dg\x3d0/ujg\x3d1/rs\x3dACT90oGquoa6r_HrWL4UF4Rytj5ElJALog',basecss:'/xjs/_/ss/k\x3dxjs.hp.QGw_2SygG64.L.X.O/am\x3dhAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAACAASBC4AAAAAAYIAAAAAAAAAAAAAAAAAAAIAAAAKgAAAQgRAABAIAAQQIAgAKASQCAAQAAAIAAoAIBkANQOgAAAAAEEAAEEAAAAgAKAAAASAAAMAAAAAIYAQAAAAAAACAAAAAAAAAAAiI/rs\x3dACT90oE7QL23plb1k3FQu5njFWzi6wtqDA',basejs:'/xjs/_/js/k\x3dxjs.hp.en.B7jo0hURfI8.es5.O/am\x3dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAEAAAAAAAAAgAAAAIQAAAQgRAABAAAAAAAAAAIAAAYAcCAAQAAAAAAAgAMAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAA4AAAAADAAwuOAAAAAAAAAAmIBQAAAAAAAAIhH/dg\x3d0/rs\x3dACT90oG2dYL8a59jo-_IjJqxdvixN1qtxQ',excm:[]};})();(function(){var u='/xjs/_/js/k\x3dxjs.hp.en.B7jo0hURfI8.es5.O/am\x3dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAEAAAAAAAAAgAAAAIQAAAQgRAABAAAAAAAAAAIAAAYAcCAAQAAAAAAAgAMAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAA4AAAAADAAwuOAAAAAAAAAAmIBQAAAAAAAAIhH/d\x3d1/ed\x3d1/dg\x3d3/rs\x3dACT90oG2dYL8a59jo-_IjJqxdvixN1qtxQ/m\x3dsb_he,d';var st=1;var amd=1000;var mmd=0;var pod=true;var pop=true;var povp=false;var fp='';
var e=this||self;function f(){var b,a,d;if(a=b=(a=window.google)==null?void 0:(d=a.ia)==null?void 0:d.r.B2Jtyd)a=b.m,a=a===1||a===5||a===6;return a&&b.cbfd!=null&&b.cbvi!=null?b:void 0};function g(){var b=[u];if(!google.dp){for(var a=0;a<b.length;a++){var d=b[a],c=document.createElement("link");c.as="script";c.href=d;c.rel="preload";document.body.appendChild(c)}google.dp=!0}};google.ps===void 0&&(google.ps=[]);function h(){var b=u,a=function(){};google.lx=google.stvsc?a:function(){k(b);google.lx=a};google.bx||google.lx()}function l(b,a){a&&(b.src=a);fp&&google.caft&&google.caft(function(){b.fetchPriority=fp});var d=b.onload;b.onload=function(c){d&&d(c);google.ps=google.ps.filter(function(G){return b!==G})};google.ps.push(b);document.body.appendChild(b)}google.as=l;function k(b){google.timers&&google.timers.load&&google.tick&&google.tick("load","xjsls");var a=document.createElement("script");a.onerror=function(){google.ple=1};a.onload=function(){google.ple=0};google.xjsus=void 0;l(a,b);google.aple=-1;google.dp=!0};function m(b){var a=b.getAttribute("jscontroller");return(a==="UBXHI"||a==="R3fhkb"||a==="TSZEqd")&&b.hasAttribute("data-src")}function n(){for(var b=document.getElementsByTagName("img"),a=0,d=b.length;a<d;a++){var c=b[a];if(c.hasAttribute("data-lzy_")&&Number(c.getAttribute("data-atf"))&1&&!m(c))return!0}return!1}for(var p=document.getElementsByTagName("img"),q=0,r=p.length;q<r;++q){var t=p[q];Number(t.getAttribute("data-atf"))&1&&m(t)&&(t.src=t.getAttribute("data-src"))};var w,x,y,z,A,B,C,D,E,F;function H(){google.xjsu=u;e._F_jsUrl=u;A=function(){h()};w=!1;x=(st===1||st===3)&&!!google.caft&&!n();y=f();z=(st===2||st===3)&&!!y&&!n();B=pod;C=pop;D=povp;E=pop&&document.prerendering||povp&&document.hidden;F=D?"visibilitychange":"prerenderingchange"}function I(){w||x||z||E||(A(),w=!0)}
setTimeout(function(){google&&google.tick&&google.timers&&google.timers.load&&google.tick("load","xjspls");H();if(x||z||E){if(x){var b=function(){x=!1;I()};google.caft(b);window.setTimeout(b,amd)}z&&(b=function(){z=!1;I()},y.cbvi.push(b),window.setTimeout(b,mmd));if(E){var a=function(){(D?document.hidden:document.prerendering)||(E=!1,I(),document.removeEventListener(F,a))};document.addEventListener(F,a,{passive:!0})}if(B||C||D)w||g()}else A()},0);})();window._ = window._ || {};window._DumpException = _._DumpException = function(e){throw e;};window._s = window._s || {};_s._DumpException = _._DumpException;window._qs = window._qs || {};_qs._DumpException = _._DumpException;(function(){var t=[132,0,1024,0,0,0,0,16384,65536,393216,951330,637534208,32,67108864,0,16,168,268436208,270811648,958660608,6083,430310426,369563648,2109450,268501664,15548430,8,17318913,33554448,10240,294912,3328,20449856,0,238821379,32,33554432,16778636,0,300023808];window._F_toggles = window._xjs_toggles = t;})();window._F_installCss = window._F_installCss || function(css){};(function(){google.jl={bfl:0,dw:false,eli:false,ine:false,ubm:false,uwp:true,vs:false};})();(function(){var pmc='{\x22d\x22:{},\x22sb_he\x22:{\x22client\x22:\x22heirloom-hp\x22,\x22dh\x22:true,\x22ds\x22:\x22\x22,\x22host\x22:\x22google.com\x22,\x22jsonp\x22:true,\x22msgs\x22:{\x22cibl\x22:\x22Clear Search\x22,\x22dym\x22:\x22Did you mean:\x22,\x22lcky\x22:\x22I\\u0026#39;m Feeling Lucky\x22,\x22lml\x22:\x22Learn more\x22,\x22psrc\x22:\x22This search was removed from your \\u003Ca href\x3d\\\x22/history\\\x22\\u003EWeb History\\u003C/a\\u003E\x22,\x22psrl\x22:\x22Remove\x22,\x22sbit\x22:\x22Search by image\x22,\x22srch\x22:\x22Google Search\x22},\x22ovr\x22:{},\x22pq\x22:\x22\x22,\x22rfs\x22:[],\x22stok\x22:\x22gFlnuhuaiu3Lza-ZG2sIvzBh0bw\x22}}';google.pmc=JSON.parse(pmc);})();</script></body></html>

In [180]:
cdxml =requests.get("https://www.w3schools.com/xml/cd_catalog.xml").text
with open("C://t//test//cd_catalog.xml","w") as op:
    op.write(cdxml)

In [183]:
columns =["TITLE","ARTIST","COUNTRY","COMPANY","PRICE","YEAR"]
dataLst=[]
with open("C://t//test//cd_catalog.xml","r") as ip:
    xml = etree.parse(ip)
    root=xml.getroot()
    for cd in root.findall("CD"):
        datadict={}
        for column in columns:
            datadict[column]=cd.find(column).text
        dataLst.append(datadict)
#converted from xml to list of dictionaries
with open("C://t//test//cd.csv",'w',newline='') as op:
    dw =csv.DictWriter(op,fieldnames=columns)
    dw.writeheader()
    dw.writerows(dataLst)

In [190]:
jsondata=requests.get("https://dummyjson.com/todos").json()
with open("C://t//test//todos.csv","w",newline="") as op:
    dw =csv.DictWriter(op,fieldnames=["id","todo","userId","completed"])
    dw.writeheader()
    dw.writerows(jsondata["todos"])

In [191]:
pip install pandas

Requirement already satisfied: pandas in c:\python311\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\python311\lib\site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vishwa\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vishwa\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [192]:
import pandas as pd

In [193]:
#Pandas ETL ---Extraction/Transformation/Loading

In [194]:
iris =pd.read_csv("C://t//test/iris.csv")

In [195]:
iris.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [197]:
iris.to_excel("C://t//test//iris.xlsx",index=False)

In [198]:
iris.to_xml("C://t//test//iris.xml")

In [200]:
iris_mini = pd.read_csv("C://t//test//iris.csv",usecols=[0,2,3])

In [201]:
iris_mini.head()

   sepal.length  petal.length  petal.width
0           5.1           1.4          0.2
1           4.9           1.4          0.2
2           4.7           1.3          0.2
3           4.6           1.5          0.2
4           5.0           1.4          0.2

In [202]:
cddf = pd.read_xml("C://t//test/cd_catalog.xml")

In [203]:
cddf.head()

                 TITLE           ARTIST COUNTRY         COMPANY  PRICE  YEAR
0     Empire Burlesque        Bob Dylan     USA        Columbia   10.9  1985
1      Hide your heart     Bonnie Tyler      UK     CBS Records    9.9  1988
2        Greatest Hits     Dolly Parton     USA             RCA    9.9  1982
3  Still got the blues       Gary Moore      UK  Virgin records   10.2  1990
4                 Eros  Eros Ramazzotti      EU             BMG    9.9  1997

In [204]:
#Generators
#are functions which are memory effective
#1000 numbers --generate one number use....
#We can create generator functions ---return ---yield
#yield is cpable of remembering value

In [205]:
def generator1(n):
    i = 1
    while i <= n:
        yield i
        i = i+1

In [206]:
gen = generator1(3)

In [207]:
next(gen)

1

In [208]:
next(gen)

2

In [209]:
next(gen)

3

In [210]:
next(gen)

StopIteration:

In [211]:
gen = generator1(3)
for i in gen:
    print(i)

1
2
3

In [212]:
for i in range(5):
    print(i)

0
1
2
3
4

In [214]:
genexpr = [i*i for i in range(3)]

In [215]:
for e in genexpr:
    print(e)

0
1
4